language: node_js
node_js:
  - "4"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14366569f6253ae6fa6c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
services:
before_install:
  - npm install -g grunt-cli
install:
  - npm install
  - cd tools/waterline-db-handler && npm install && cd ../..
  - node travis.js install
before_script:
  - mysql -e 'create database redh00d_test;'